In [30]:
import pandas as pd
import numpy as np

In [31]:
dp = pd.read_csv("kepler_data.csv")

In [32]:
dp.head()

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

1. EXPLORATORY ANALYSIS - Missing values, outliers

In [33]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 47 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   kepid              9564 non-null   int64
 1   kepoi_name         9564 non-null   object
 2   kepler_name        2360 non-null   object
 3   koi_disposition    9564 non-null   object
 4   koi_pdisposition   9564 non-null   object
 5   koi_score          8054 non-null   float64
 6   koi_fpflag_nt      9564 non-null   int64
 7   koi_fpflag_ss      9564 non-null   int64
 8   koi_fpflag_co      9564 non-null   int64
 9   koi_fpflag_ec      9564 non-null   int64
 10  koi_period         9564 non-null   float64
 11  koi_period_err1    9110 non-null   float64
 12  koi_period_err2    9110 non-null   float64
 13  koi_time0bk        9564 non-null   float64
 14  koi_time0bk_err1   9110 non-null   float64
 15  koi_time0bk_err2   9110 non-null   float64
 16  koi_impact         9201 non-null   float64
 17  koi_impact_err1    9110 non-null   float64
 18  koi_impact_err2    9110 non-null   float64
 19  koi_duration       9564 non-null   float64
 20  koi_duration_err1  9110 non-null   float64
 21  koi_duration_err2  9110 non-null   float64
 22  koi_depth          9201 non-null   float64
 23  koi_depth_err1     9110 non-null   float64
 24  koi_depth_err2     9110 non-null   float64
 25  koi_prad           9201 non-null   float64
 26  koi_prad_err1      9201 non-null   float64
 27  koi_prad_err2      9201 non-null   float64
 28  koi_teq            9201 non-null   float64
 29  koi_insol          9243 non-null   float64
 30  koi_insol_err1     9243 non-null   float64
 31  koi_insol_err2     9243 non-null   float64
 32  koi_model_snr      9201 non-null   float64
 33  koi_tce_plnt_num   9218 non-null   float64
 34  koi_tce_delivname  9218 non-null   object
 35  koi_steff          9201 non-null   float64
 36  koi_steff_err1     9096 non-null   float64
 37  koi_steff_err2     9081 non-null   float64
 38  koi_slogg          9201 non-null   float64
 39  koi_slogg_err1     9096 non-null   float64
 40  koi_slogg_err2     9096 non-null   float64
 41  koi_srad           9201 non-null   float64
 42  koi_srad_err1      9096 non-null   float64
 43  koi_srad_err2      9096 non-null   float64
 44  ra                 9564 non-null   float64
 45  dec                9564 non-null   float64
 46  koi_kepmag         9563 non-null   float64
dtypes: float64(37), int64(5), object(5)
memory usage: 3.4+ MB

In [34]:
dp.describe()

,kepid,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
count,9.564000e+03,8054.000000,9564.000000,9564.000000,9564.000000,9564.000000,9564.000000,9110.000000,9110.000000,9564.000000,...,9081.000000,9201.000000,9096.000000,9096.000000,9201.000000,9096.000000,9096.000000,9564.000000,9564.000000,9563.000000
mean,7.690628e+06,0.480829,0.208595,0.232748,0.197512,0.120033,75.671358,0.002148,-0.002148,166.183251,...,-162.265059,4.310157,0.120738,-0.143161,1.728712,0.362292,-0.394806,292.060163,43.810433,14.264606
std,2.653459e+06,0.476928,4.767290,0.422605,0.398142,0.325018,1334.744046,0.008243,0.008243,67.918960,...,72.746348,0.432606,0.132837,0.085477,6.127185,0.930870,2.168213,4.766657,3.601243,1.385448
min,7.574500e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.241843,0.000000,-0.173000,120.515914,...,-1762.000000,0.047000,0.000000,-1.207000,0.109000,0.000000,-116.137000,279.852720,36.577381,6.966000
25%,5.556034e+06,0.000000,0.000000,0.000000,0.000000,0.000000,2.733684,0.000005,-0.000276,132.761718,...,-198.000000,4.218000,0.042000,-0.196000,0.829000,0.129000,-0.250000,288.660770,40.777173,13.440000
50%,7.906892e+06,0.334000,0.000000,0.000000,0.000000,0.000000,9.752831,0.000035,-0.000035,137.224595,...,-160.000000,4.438000,0.070000,-0.128000,1.000000,0.251000,-0.111000,292.261125,43.677504,14.520000
75%,9.873066e+06,0.998000,0.000000,0.000000,0.000000,0.000000,40.715178,0.000276,-0.000005,170.694603,...,-114.000000,4.543000,0.149000,-0.088000,1.345000,0.364000,-0.069000,295.859160,46.714611,15.322000
max,1.293514e+07,1.000000,465.000000,1.000000,1.000000,1.000000,129995.778400,0.173000,0.000000,1472.522306,...,0.000000,5.364000,1.472000,0.000000,229.908000,33.091000,0.000000,301.720760,52.336010,20.003000

In [35]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
dp['koi_pdisposition'] = label_encoder.fit_transform(dp['koi_pdisposition']) 
dp['koi_disposition'] = label_encoder.fit_transform(dp['koi_disposition']) 

dp.head()

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,1,0,1.000,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,1,0,0.969,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,0,0,0.000,0,0,0,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,2,1,0.000,0,1,0,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,1,0,1.000,0,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [36]:
## droping un-useful columns and removing columns if the missing values are more than 200
dp = dp.drop(columns = ['kepid', 'kepoi_name', 'kepler_name', 'koi_tce_delivname'])
dp = dp.pipe(lambda df: df.loc[:, (df.isnull().sum(axis='rows') < 500).where(lambda v: v).dropna().index.values]).dropna()

In [37]:
dp.loc[dp['koi_fpflag_nt'] == 465, 'koi_fpflag_nt'] = 1

In [38]:
dp.head()

,koi_disposition,koi_pdisposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,0,0,0,0,0,9.488036,2.780000e-05,-2.780000e-05,170.538750,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,1,0,0,0,0,0,54.418383,2.480000e-04,-2.480000e-04,162.513840,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,0,0,0,0,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,2,1,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,1,0,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [39]:
y = dp.iloc[:,0]
X = dp.iloc[:, 1:]

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=.40)

### PCA - Principal Component Analysis for feature selection

In [41]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


from sklearn.decomposition import PCA
pca = PCA(.80)

pca.fit(X_train)


train_img = pca.transform(X_train)
test_img = pca.transform(X_test)

### Models - 
###  1.) Logistic Regression
### 2.) Decision Trees
### 3.) random forest classifier

In [42]:
from sklearn import metrics
from sklearn.metrics import mean_squared_error, precision_score, confusion_matrix, accuracy_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [43]:
lr = LogisticRegression(C = 0.01, max_iter = 100, penalty = 'l2')
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [44]:
print('Evaluation Metrics:')
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred)))
print('Recall: ' + str(recall_score(y_test, y_pred, average = 'micro')))
print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred, average = 'micro')))
print('Precision: ' + str(metrics.precision_score(y_test, y_pred, average = 'micro')))
print('\nConfusion Matrix:')
print(' TN,  FP, FN, TP')
confusion_matrix(y_test, y_pred)

Evaluation Metrics:
Accuracy: 0.8790737564322469
Recall: 0.8790737564322469
F1 Score: 0.8790737564322469
Precision: 0.8790737564322469

Confusion Matrix:
 TN,  FP, FN, TP

array([[ 579,  292,    0],
       [ 127,  803,    2],
       [   1,    1, 1693]], dtype=int64)

In [45]:
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)
print('Evaluation Metrics:')
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred)))
print('Recall: ' + str(recall_score(y_test, y_pred, average = 'micro')))
print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred, average = 'micro')))
print('Precision: ' + str(metrics.precision_score(y_test, y_pred, average = 'micro')))
print('\nConfusion Matrix:')
print(' TN,  FP, FN, TP')
confusion_matrix(y_test, y_pred)

Evaluation Metrics:
Accuracy: 0.875071469411092
Recall: 0.875071469411092
F1 Score: 0.875071469411092
Precision: 0.875071469411092

Confusion Matrix:
 TN,  FP, FN, TP

array([[ 649,  222,    0],
       [ 205,  725,    2],
       [   0,    8, 1687]], dtype=int64)

In [46]:
forest = RandomForestClassifier(n_estimators=100, criterion='gini', max_features = 'log2')
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)
print('Evaluation Metrics:')
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred)))
print('Recall: ' + str(recall_score(y_test, y_pred, average = 'micro')))
print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred, average = 'micro')))
print('Precision: ' + str(metrics.precision_score(y_test, y_pred, average = 'micro')))
print('\nConfusion Matrix:')
print(' TN,  FP, FN, TP')
confusion_matrix(y_test, y_pred)

Evaluation Metrics:
Accuracy: 0.9108061749571184
Recall: 0.9108061749571184
F1 Score: 0.9108061749571184
Precision: 0.9108061749571184

Confusion Matrix:
 TN,  FP, FN, TP

array([[ 700,  171,    0],
       [ 138,  792,    2],
       [   0,    1, 1694]], dtype=int64)

<b>Why did you choose the particular algorithm?</b><br>
On analysing the dependent variable, we know the problem falls in the category of classification in supervised learning.
Then, we apply different classification algorithms and look into the following results -
Accuracy of the model
Time complexity
Results on the test data
By trial and error on the potential algorithms, we find the one giving highest accuracy.
In this case, we find that random forests works better than decision trees and logistic regression

<b>What are the different tuning methods used for the algorithm?</b><br>
Tuning the hyper parameters - 
Logistic Regression - we can use different values of C(penalty strength) and penalty type(l2, l1) <br>
Decision Trees - max_depth, min_samples_split, max_features <br>
Random Forests - max_features and n_estimators

<b>Did you consider any other choice of algorithm?Why or why not?</b><br>
We can go from most basic classification algorithms to most advanced - 
We can also look into other classification algorithms such as knn classifier, SVM.
We can also go deep into boosting, and try applying gradient boost, xgboost.

<b>What is the accuracy?</b><br>
Accuracy is number of right predictions in the model.<br>
The highest accuracy in this case is reached by random forests - ~0.92

<b>What are the different types of metrics that can be used to evaluate the model?</b><br>
The different types of metrics used for classification models are - <br>
Confusion Metrics is highly used.<br>
Apart from that - Precision, Recall, F1 Score, Accuracy